export function downloadTextFile(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  triggerDownload(filename, blob);
}

export function downloadJsonFile(filename: string, data: unknown) {
  const blob = new Blob([JSON.stringify(data, null, 2)], {
    type: "application/json;charset=utf-8",
  });

  triggerDownload(filename, blob);
}

export function downloadCsvFile(
  filename: string,
  rows: Record<string, unknown>[]
) {
  if (!rows.length) {
    downloadTextFile(filename, "");
    return;
  }

  const headers = Object.keys(rows[0]);

  const csv = [
    headers.join(","),
    ...rows.map((row) =>
      headers
        .map((header) => {
          const value = row[header] ?? "";
          return `"${String(value).replace(/"/g, '""')}"`;
        })
        .join(",")
    ),
  ].join("\n");

  const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
  triggerDownload(filename, blob);
}

export function copyTextToClipboard(content: string) {
  if (navigator.clipboard && window.isSecureContext) {
    return navigator.clipboard.writeText(content);
  }

  const textArea = document.createElement("textarea");
  textArea.value = content;
  textArea.style.position = "fixed";
  textArea.style.left = "-999999px";
  textArea.style.top = "-999999px";
  document.body.appendChild(textArea);
  textArea.focus();
  textArea.select();

  return new Promise<void>((resolve, reject) => {
    try {
      document.execCommand("copy");
      textArea.remove();
      resolve();
    } catch (error) {
      textArea.remove();
      reject(error);
    }
  });
}

export function openPrintableReport(params: {
  title: string;
  subtitle?: string;
  report: string;
  metadata?: Record<string, string | number>;
}) {
  const printWindow = window.open("", "_blank", "width=900,height=1100");

  if (!printWindow) {
    alert("Popup blocked. Please allow popups to export the report.");
    return;
  }

  const metadataHtml = params.metadata
    ? Object.entries(params.metadata)
        .map(
          ([key, value]) =>
            `<div class="meta-row"><span>${escapeHtml(key)}</span><strong>${escapeHtml(
              String(value)
            )}</strong></div>`
        )
        .join("")
    : "";

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${escapeHtml(params.title)}</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            margin: 40px;
            color: #0f172a;
            line-height: 1.6;
          }

          .header {
            border-bottom: 3px solid #0891b2;
            padding-bottom: 18px;
            margin-bottom: 24px;
          }

          .brand {
            color: #0891b2;
            font-size: 13px;
            font-weight: 700;
            letter-spacing: 0.08em;
            text-transform: uppercase;
          }

          h1 {
            margin: 8px 0 4px;
            font-size: 30px;
          }

          .subtitle {
            color: #475569;
            margin: 0;
          }

          .metadata {
            display: grid;
            grid-template-columns: repeat(2, minmax(0, 1fr));
            gap: 12px;
            margin: 24px 0;
          }

          .meta-row {
            border: 1px solid #cbd5e1;
            border-radius: 10px;
            padding: 12px;
            background: #f8fafc;
          }

          .meta-row span {
            display: block;
            color: #64748b;
            font-size: 12px;
            text-transform: uppercase;
          }

          .meta-row strong {
            display: block;
            margin-top: 4px;
            color: #0f172a;
          }

          pre {
            white-space: pre-wrap;
            border: 1px solid #cbd5e1;
            border-radius: 12px;
            padding: 20px;
            background: #f8fafc;
            font-size: 14px;
          }

          .footer {
            margin-top: 28px;
            color: #64748b;
            font-size: 12px;
            border-top: 1px solid #cbd5e1;
            padding-top: 14px;
          }

          @media print {
            body {
              margin: 24px;
            }

            button {
              display: none;
            }
          }
        </style>
      </head>

      <body>
        <div class="header">
          <div class="brand">OmniSignal AI</div>
          <h1>${escapeHtml(params.title)}</h1>
          <p class="subtitle">${escapeHtml(
            params.subtitle || "Enterprise AI Intelligence Report"
          )}</p>
        </div>

        ${metadataHtml ? `<div class="metadata">${metadataHtml}</div>` : ""}

        <pre>${escapeHtml(params.report)}</pre>

        <div class="footer">
          Generated by OmniSignal AI. Use your browser print dialog to save this report as PDF.
        </div>

        <script>
          window.onload = function () {
            setTimeout(function () {
              window.print();
            }, 400);
          };
        </script>
      </body>
    </html>
  `;

  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();
}

function triggerDownload(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();

  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}


